### ISSUE TITLE
Recent release made it slower and sort not as well...

### ISSUE THREAD

**Issue by kentcdodds** [ritz078/emoji-assistant#8]
Here's an example:

![slower](https://user-images.githubusercontent.com/1500684/28897002-07f573c4-779c-11e7-8407-c6e92f37cef7.gif)

I think for the sorting, we could use [`match-sorter`](https://github.com/kentcdodds/match-sorter). That's a great sorting solution (I am biased)

For the performance, I'm not sure what's going on there.

How can I help?

**Comment by ritz078** [comment]
Its because for using AI, I am using an API. It helps people who don't know the exact emoji name. Currently top few results are smart then the general results come (which are sorted using js-search). I have 2 solutions 
- remove smart suggestions.
- make it optional.

Any other suggestion you have ?

I am looking to bring back the old behaviour.

**Comment by kentcdodds** [comment]
That's cool! You could use AI, but then sort the results using match-sorter. It's job is to sort things in a way that's intuitive to the user (because right now js-search isn't intuitive).

**Comment by ritz078** [comment]
Sure. I will try that.

**Comment by kentcdodds** [comment]
Great! Thank you! 🙏

**Comment by kentcdodds** [comment]
As for performance, I'm guessing the AI is what's causing issues. I wonder if we could make that configurable so I can disable it myself (because I generally know what I'm looking for and would rather it be faster).
